### ISSUE TITLE
database required

### ISSUE THREAD

**Issue by Chiaooo** [sirajuddin97/UserControlPanel#1]
Thanks for your ucp excellent work!
But I want to develop the ucp for my own role play server,and it seems that some tables couldn't match my database,but I don't know which table I should create and the type or character.
Could u release the empty database just for the tables?
many thanks!

**Comment by Chiaooo** [comment]
And I don't see any register.php but I found function about register in ajax folder

**Comment by Ranneciva** [comment]
I have same issues, could you release the empty table for us? @sirasjad

**Comment by sirasjad** [comment]
I don't have the database file anymore, deleted it long time ago. Sorry.
