### ISSUE TITLE
Issue with copyright

### ISSUE THREAD

**Issue by foola1** [sirajuddin97/UserControlPanel#2]
Hello @sirasjad. I noticed a Project Reality Roleplay clone use your work and removed your credits. I support open-source work and feel people should not steal work and claim its there.

Here's a [link to the offending material](http://www.project-rp.net/ucp/).

I hope you are able to take any action as the owners of that community are scamming teenagers for their low effort clone.

**Comment by Chaprnks** [comment]
After digging around the site, I obtained the Gmail the server uses to send emails (ironically not an email on the domain it should be sending from). Might help get in contact with them, if he does wish to persue this.

lielr10@gmail.com


---


To make it more offensive, it seems they have replaced your credits with their own.. claiming they made this all on their own, without mentioning you.

Design and coding by ak1smet

**Comment by sirasjad** [comment]
I will contact the site owner and ask him why he removed the credits. Thanks for letting me know!

**Comment by sirasjad** [comment]
@foola1 @Chaprnks I tried to contact the site owner on the community forums, but as response he IP banned me. Not so cooperative this guy..

**Comment by Chaprnks** [comment]
Not too surprising.. seeing as he claimed the work as his own.. If you don't want his work to remain uncredited, I'd recommend filing a DMCA copyright complaint. Then he will be forced to include rights or be served with a seize & desist order. I've never personally filed one of those complaints for something of my work, but I have assisted a friend in getting his work credited by helping him file with the appropriate authority. If you do wish to pursue this further, I'd be more than happy to assist you. If not, no worries. Side note, great work on the UCP! Probably the best looking UCP's I've ever seen publicly released for SA-MP :)

**Comment by sirasjad** [comment]
I got ahold of the community owner on Discord and discussed it with him. He agreed to add credits. 

Thanks anyways for letting me know, I appreciate it.
